on: [push]
jobs:
  run_tests:
    runs-on: ubuntu-latest
    name: Run Tests
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - run: yarn
      - run: npx lerna run build
      - run: yarn audit-deps
      - run: yarn lint
      - run: yarn test
      - run: yarn build-storybook
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs-build
